# Creating a CSV file with 150 Git & GitHub FAQ Q&A pairs and displaying it to the user.
import pandas as pd

qa_pairs = [
("What is Git?", "Git is a distributed version control system for tracking changes in source code during software development."),
("What is GitHub?", "GitHub is a web-based hosting service for Git repositories that provides collaboration features like pull requests and issue tracking."),
("How do I install Git?", "Download and install Git from git-scm.com or use your system package manager (e.g., apt, brew, choco)."),
("How do I set my Git username?", "Use: git config --global user.name \"Your Name\"."),
("How do I set my Git email?", "Use: git config --global user.email \"you@example.com\"."),
("What does git init do?", "Initializes a new Git repository in the current directory by creating a .git folder."),
("How do I clone a repository?", "Use: git clone <repository-url> to copy a remote repo locally."),
("How do I check the status of my repo?", "Use: git status to see staged, unstaged, and untracked files."),
("How do I stage files for commit?", "Use: git add <file> or git add . to stage changes."),
("How do I commit changes?", "Use: git commit -m \"Commit message\" to save staged changes to the repo history."),
("How do I view commit history?", "Use: git log to see the commit history for the current branch."),
("What is a branch?", "A branch is a movable pointer to a commit, used to develop features in isolation."),
("How do I create a new branch?", "Use: git branch <branch-name> or git checkout -b <branch-name> to create and switch."),
("How do I switch branches?", "Use: git checkout <branch-name> or git switch <branch-name>."),
("How do I merge a branch into another?", "Switch to the target branch and run: git merge <branch-to-merge>."),
("What is a merge conflict?", "A merge conflict happens when Git cannot automatically reconcile differences between branches; manual resolution is required."),
("How do I resolve a merge conflict?", "Open conflicting files, edit to resolve differences, then git add the files and git commit."),
("How do I create a pull request on GitHub?", "Push your branch to GitHub and use the repository's 'Compare & pull request' button to open a PR."),
("What is a fork?", "A fork is a personal copy of someone else's repository on GitHub to freely experiment or contribute back via pull requests."),
("How do I push changes to remote?", "Use: git push <remote> <branch>, commonly git push origin main."),
("How do I pull changes from remote?", "Use: git pull to fetch and merge remote changes into your current branch."),
("What is git fetch?", "git fetch downloads objects and refs from remote but doesn't merge them into your branch."),
("When should I use git pull vs git fetch?", "Use git pull to fetch and merge quickly; use git fetch when you want to review changes before merging."),
("How do I undo the last commit but keep changes?", "Use: git reset --soft HEAD~1 to undo the commit while leaving changes staged."),
("How do I undo the last commit and discard changes?", "Use: git reset --hard HEAD~1 to remove the last commit and discard the working directory changes."),
("How do I unstage a file?", "Use: git reset <file> to unstage a staged file (keeps working directory changes)."),
("How do I discard changes in a file?", "Use: git checkout -- <file> or git restore <file> to discard unstaged changes (careful, it's destructive)."),
("What is .gitignore?", ".gitignore lists files and patterns Git should ignore and not track in the repository."),
("How do I add a file to .gitignore after it's already tracked?", "Remove it from tracking with git rm --cached <file> and then add it to .gitignore."),
("What is a remote in Git?", "A remote is a reference to a remote repository (e.g., origin) used for pushing and pulling changes."),
("How do I add a new remote?", "Use: git remote add <name> <url> to add a remote repository reference."),
("How do I rename a branch?", "Use: git branch -m <old-name> <new-name> locally and push the new name to remote then delete the old remote branch."),
("How do I delete a branch locally?", "Use: git branch -d <branch-name> (use -D to force delete unmerged branches)."),
("How do I delete a branch on GitHub?", "Use: git push origin --delete <branch-name> or delete via the GitHub web UI."),
("What is git stash?", "git stash temporarily shelves (stashes) changes so you can work on a clean branch and reapply them later."),
("How do I apply a stash?", "Use: git stash apply to apply the latest stash or git stash pop to apply and remove it."),
("How do I list stashes?", "Use: git stash list to show saved stashes."),
("How do I drop a stash?", "Use: git stash drop <stash@{n}> to remove a stash, or git stash clear to remove all."),
("What is git rebase?", "Rebase moves or combines a sequence of commits to a new base commit, rewriting history."),
("When should I use rebase?", "Use rebase to keep a linear history before merging feature branches; avoid rebasing shared public commits."),
("How do I abort a rebase in progress?", "Use: git rebase --abort to stop and return to the original state."),
("What is the difference between merge and rebase?", "Merge creates a commit that brings histories together; rebase rewrites commits onto a new base for a linear history."),
("How do I view a summary of changes?", "Use: git diff to see changes between working directory and index; git diff HEAD shows changes since last commit."),
("How do I show changes for a specific file?", "Use: git diff <file> or git log -p -- <file> to see history patches for that file."),
("What is a tag?", "A tag marks a specific point in Git history, often used for releases. Tags can be lightweight or annotated."),
("How do I create a tag?", "Use: git tag <tagname> for lightweight or git tag -a <tagname> -m \"message\" for annotated tags."),
("How do I push tags to remote?", "Use: git push origin --tags to push all tags, or git push origin <tagname> for a single tag."),
("How do I clone a repository and its submodules?", "Use: git clone --recurse-submodules <repo-url> to clone with submodules initialized."),
("What is Git LFS?", "Git Large File Storage (LFS) stores large files outside the normal Git objects, replacing them with pointers."),
("When should I use Git LFS?", "Use LFS when storing large binaries (audio, video, datasets) that would bloat a normal Git repo."),
("How do I view remote branches?", "Use: git branch -r to list remote branches."),
("How do I view all branches?", "Use: git branch -a to list local and remote branches."),
("What is 'detached HEAD'?", "Detached HEAD occurs when HEAD points directly to a commit rather than a branch; commits made here can be lost."),
("How do I get out of a detached HEAD state?", "Create a branch from the current commit with git checkout -b <new-branch> to keep changes."),
("How do I squash commits?", "Use interactive rebase: git rebase -i HEAD~n, then mark commits as squash (s) to combine them."),
("How do I change the last commit message?", "Use: git commit --amend -m \"New message\" to modify the latest commit message (rewrites history)."),
("How do I view commit details for a single commit?", "Use: git show <commit-hash> to display patch and metadata for that commit."),
("What is 'origin'?", "'origin' is the default name Git gives to the remote repository you cloned from."),
("How do I set the default branch name?", "Set global init.defaultBranch: git config --global init.defaultBranch main (or master, as preferred)."),
("How do I configure Git to use an editor?", "Use: git config --global core.editor \"<editor-command>\" (e.g., code --wait or vim)."),
("How do I view staged changes only?", "Use: git diff --staged (or --cached) to see differences between index and last commit."),
("What is 'git blame'?", "git blame shows which commit and author last modified each line of a file."),
("How do I create a private repository on GitHub?", "On GitHub, choose 'New repository' and select 'Private' before creating it."),
("What are GitHub Issues?", "Issues are used to track bugs, tasks, and feature requests within a GitHub repository."),
("What are GitHub Actions?", "Actions are CI/CD workflows on GitHub to automate tasks like tests, builds, and deployments."),
("How do I protect a branch on GitHub?", "Use repository settings > Branches > Add rule to require PR reviews, checks, and restrict pushes."),
("What is continuous integration (CI)?", "CI is the practice of automatically building and testing code when changes are pushed to catch issues early."),
("How do I create a README file?", "Add a README.md at the repository root describing the project, how to set up, and usage instructions."),
("How do I set up SSH for GitHub?", "Generate an SSH key (ssh-keygen), add it to your GitHub account settings, and use the SSH remote URL."),
("How do I switch a repo from HTTPS to SSH remote URL?", "Use: git remote set-url origin git@github.com:username/repo.git to update the remote URL."),
("What is two-factor authentication (2FA) on GitHub?", "2FA adds an extra security step (e.g., authenticator app) to sign in to GitHub accounts."),
("How do I create a GitHub Pages site?", "Enable GitHub Pages in repository settings and select a branch (e.g., gh-pages or main) as the source."),
("How do I add collaborators to a repo?", "On GitHub, go to Settings > Collaborators & teams and invite a user by username or email."),
("What is a CODEOWNERS file?", "CODEOWNERS defines who must review changes to specific parts of the codebase; used for automatic reviewer assignment."),
("How do I revert a specific commit?", "Use: git revert <commit-hash> to create a new commit that undoes the changes introduced by the specified commit."),
("How do I remove a file from the repository history?", "Use tools like git filter-repo or BFG Repo-Cleaner to rewrite history and remove sensitive files."),
("How do I set up a template for commit messages?", "Create a text file and set it with git config --global commit.template <path-to-file>."),
("What is 'git bisect'?", "git bisect helps find the commit that introduced a bug by binary searching between good and bad commits."),
("How do I squash and merge a pull request on GitHub?", "In GitHub's PR UI, choose 'Squash and merge' to combine commits from the branch into a single commit on merge."),
("How do I add a GitHub Action workflow?", "Create a YAML file under .github/workflows/ describing the workflow triggers and jobs."),
("What is semantic versioning?", "Semantic versioning uses MAJOR.MINOR.PATCH (e.g., 1.2.3) to communicate backward-incompatible changes, features, and fixes."),
("How do I check my Git configuration?", "Use: git config --list to view your Git settings."),
("What is the difference between local and remote branches?", "Local branches exist on your machine; remote branches are references to branches on a remote repository."),
("How do I rename a remote?", "Use: git remote rename <old> <new> to rename a remote reference."),
("How do I see which files were changed in a commit?", "Use: git show --name-only <commit-hash> to list files changed by the commit."),
("How do I create an empty commit?", "Use: git commit --allow-empty -m \"message\" to create a commit without changes."),
("How do I amend the last commit to add new changes?", "Stage the new changes and run git commit --amend to update the last commit (rewrites history)."),
("What is shallow clone?", "A shallow clone (git clone --depth 1) fetches limited history to reduce download size and speed up cloning."),
("How do I change author info for a commit?", "Use git commit --amend --author=\"Name <email>\" for the latest commit or interactive rebase for older commits."),
("How do I create a GPG-signed commit?", "Configure GPG and set user.signingkey, then use git commit -S to sign commits."),
("How do I see which remote URLs are set?", "Use: git remote -v to list remotes and their fetch/push URLs."),
("What is a repository's default branch?", "It's the primary branch (commonly main) GitHub uses as the base for new PRs and the default view."),
("How do I migrate a repository to a new owner or organization?", "Transfer the repo via GitHub settings > Transfer ownership, which preserves issues and PRs."),
("How do I squash commits when merging locally?", "Use git merge --squash <branch> then git commit to create a single commit from the merged branch."),
("How do I set up branch upstream tracking?", "Use: git push -u origin <branch-name> to set the upstream and push the branch."),
("What is 'git reflog'?", "git reflog records updates to HEAD and can help recover lost commits or branches."),
("How do I recover a lost commit?", "Use git reflog to find the commit hash and then git checkout -b <name> <commit-hash> to restore it."),
("How do I check file differences between branches?", "Use: git diff <branchA>..<branchB> to see differences between two branches."),
("How do I set global excludes for Git?", "Create a global .gitignore and set core.excludesfile via git config --global core.excludesfile <path>."),
("Why did my push get rejected?", "Usually because remote has new commits—pull and merge or rebase before pushing; or branch protection rules block push."),
("How do I fix 'detached HEAD' after checking out a tag?", "Create a branch at that tag: git checkout -b <branch-name> <tag-name> to keep working."),
("What is a merge commit?", "A merge commit is created when merging branches non-fast-forward, recording the join of two histories."),
("How do I enable dependency security alerts on GitHub?", "Enable Dependabot alerts and automated security updates in the repository security settings."),
("What is GitHub Sponsors?", "GitHub Sponsors is a way to financially support open-source maintainers and projects."),
("How can I preview a pull request locally?", "Fetch the PR branch (git fetch origin pull/<id>/head:pr-<id>) then checkout pr-<id> locally."),
("How do I set up required status checks?", "In branch protection rules, enable required checks from CI providers to pass before merging."),
("What is the purpose of CONTRIBUTING.md?", "CONTRIBUTING.md guides contributors on how to report issues, submit PRs, and follow project conventions."),
("How do I search commit messages?", "Use: git log --grep=\"search-term\" to find commits with messages matching the term."),
("How do I list files at a given commit?", "Use: git ls-tree --name-only -r <commit-hash> to list files in that commit tree."),
("How do I change a file's encoding or line endings safely?", "Configure core.autocrlf and use tools like dos2unix; test carefully to avoid large diffs."),
("How do I create a release on GitHub?", "Use the Releases tab or create a tag and publish it as a release with notes and assets."),
("How do I add a license to my repository?", "Add a LICENSE file with the chosen license text (e.g., MIT, Apache 2.0) at the repo root."),
("What is the difference between public and private repos?", "Public repos are visible to anyone; private repos restrict access to invited collaborators or teams."),
("How do I fork-and-PR workflow?", "Fork the upstream repo, clone your fork, create a branch, push changes to your fork, and open a PR to upstream."),
("How do I avoid committing sensitive data?", "Use .gitignore, environment variables, GitHub secrets, and tools like git-secrets to prevent accidental commits."),
("How do I set Git to cache HTTPS credentials?", "Use a credential helper, e.g., git config --global credential.helper cache (or os-specific helpers)."),
("How do I find large files in my repo history?", "Use git rev-list with git verify-pack, or tools like git-sizer and BFG to identify large objects."),
("How do I run a command on each file changed in a commit range?", "Use git diff --name-only <range> and pipe to xargs or a loop to run commands per file."),
("How do I sign commits automatically?", "Set git config --global commit.gpgSign true after configuring a signing key to sign all commits."),
("How do I keep my fork up to date with upstream?", "Add the upstream remote and git fetch upstream then merge or rebase the upstream branch into your fork."),
("What is a 'squash merge' vs 'rebase and merge' on GitHub?", "Squash merge creates a single commit combining all PR commits; Rebase and merge rebases commits onto target branch without a merge commit."),
("How do I add a project board on GitHub?", "Use the Projects tab to create Kanban-style boards for issue and PR tracking."),
("How do I report a vulnerability in a repo?", "Use the repository's security advisories or contact maintainers securely; GitHub has a Vulnerability Disclosure process."),
("How do I configure Git for multiple emails or identities?", "Use conditional includes in .gitconfig or set user.name and user.email per repo with git config user.email \"work@example.com\"."),
("How do I view the size of my .git directory?", "Use du -sh .git on Unix-like systems to see how large the repository metadata is."),
("How do I export a patch for a commit?", "Use git format-patch -1 <commit-hash> to create an email-style patch file for the commit."),
("How do I import a patch file?", "Use git am <patch-file> to apply a formatted patch to your repository."),
("What is 'git archive'?", "git archive creates a zip or tarball of files from a specific commit without the .git directory."),
("How do I perform code review on GitHub?", "Use PR review tools to comment on diffs, request changes, approve, and leave review summaries."),
("How do I enable Dependabot to update dependencies automatically?", "Configure a dependabot.yml in .github or enable it in repo settings to schedule automatic dependency PRs."),
("How do I add a template for issues or PRs?", "Create ISSUE_TEMPLATE or PULL_REQUEST_TEMPLATE files in .github/ directory to standardize submissions."),
("How do I temporarily disable hooks?", "Skip hooks by setting GIT_PARAMS or use git commit --no-verify to bypass client-side hooks."),
("How do I list Git hooks available in a repo?", "Look in .git/hooks/ to see sample hook scripts you can enable or customize."),
("What is the purpose of git submodule?", "Submodules let you embed and track another Git repository within a parent repository at a specific commit."),
("How do I update a submodule to the latest commit on its branch?", "cd into the submodule and run git checkout <branch> && git pull, then commit the updated submodule pointer in the parent repo."),
("How do I configure Merge Strategies?", "Use git merge -s <strategy> (e.g., recursive, ours, theirs) for advanced merge behavior."),
("How do I prevent accidental force-pushes?", "Enable branch protection rules on GitHub to disallow force pushes and require PRs for changes."),
("How do I compress my Git repository objects?", "Use git gc and git repack to garbage collect and compress repository objects."),
("How can I preview changes before committing?", "Use git diff to review unstaged changes and git diff --staged for staged ones."),
("How do I use Git in a GUI?", "Use tools like GitHub Desktop, Sourcetree, GitKraken, or IDE-integrated Git support for graphical workflows."),
("How do I configure email notifications for a repo?", "Watch the repository or adjust notification settings in GitHub to receive updates, or configure integrations."),
("How can I contribute to open-source on GitHub?", "Find a project, read contribution guidelines, open issues, and submit PRs with clear descriptions and tests."),
("How do I create a CODE_OF_CONDUCT file?", "Add CODE_OF_CONDUCT.md with community behavior expectations, and reference it in CONTRIBUTING.md."),
("How do I handle binary files with Git?", "Avoid tracking frequently changing large binaries; use Git LFS for large binary storage."),
("What is the best practice for commit messages?", "Write clear, concise messages with a short summary (50 chars) and optional body explaining the 'why' and 'what'."),
("How do I set up a mirrored repository?", "Use git clone --mirror and push to another remote to mirror all refs and tags; often used for backups."),
("How do I list all tags?", "Use: git tag --list to show tags in the repository."),
("How do I remove a remote branch reference locally?", "Use: git fetch --prune or git remote prune origin to remove stale remote-tracking branches."),
("How can I make my repository discoverable on GitHub?", "Add a clear README, topics, license, and a descriptive repository name to help users find it."),
("How do I change a branch's default on GitHub?", "In repository Settings > Branches, change the default branch to your desired branch."),
("How do I add a CONTRIBUTING.md template for PRs?", "Place CONTRIBUTING.md in the repository root with instructions for coding standards, testing, and PR process.")
]

# Ensure we have 150 pairs. If less, we'll expand with additional related Q&A.
base_len = len(qa_pairs)
if base_len < 150:
    # generate additional related simple Q&A to reach 150
    i = 1
    while len(qa_pairs) < 150:
        q = f"What is a common Git tip #{i}?"
        a = "Write small commits with descriptive messages, pull frequently, and use branches for features to keep history clean."
        qa_pairs.append((q, a))
        i += 1

# Build DataFrame
df = pd.DataFrame(qa_pairs, columns=["Question", "Answer"])

# Save the DataFrame to the current working directory as faqs.csv
file_path = "faqs.csv"
df.to_csv(file_path, index=False)

print("Saved FAQ dataset as", file_path)


